### ISSUE TITLE
The Source Code & API link is broken on pages other than home page

### ISSUE THREAD

**Issue by ILM126** [KSP-SpaceDock/KerbalStuff#39]
"Source Code" links to "https://github.com/KSP-SpaceDock/KerbalStuff"
And the "API" links to "https://github.com/KSP-SpaceDock/KerbalStuff/blob/master/api.md"

But in other pages, it shows this.
"http://spacedock.info/mod/52/" and
"http://spacedock.info/blob/master/api.md"

I also took a peek at the template and it shows this.

<li><a href="{{ source_code }}">Source Code</a></li>
<li><a href="{{ source_code }}/blob/master/api.md">API</a></li>

**Comment by godarklight** [comment]
Note that the actual API itself appears to be working: http://spacedock.info/api/mod/10 - but yeah this is something to fix up :)

**Comment by ILM126** [comment]
Huh, I can't assign myself with this.

**Comment by ILM126** [comment]
Pull 40, https://github.com/KSP-SpaceDock/KerbalStuff/pull/40
