### ISSUE TITLE
Word Replacement Mistake!

### ISSUE THREAD

**Issue by ThaZeus** [KSP-SpaceDock/KerbalStuff#9]
In the about Space Dock section it says this:  "There have been a few poor modding sites for Space Dock Program in the past."  Probably just a quick fix but i thought it should come to your attention!

**Comment by Electro-ninja** [comment]
Okay I have poured over the entire repository, and I can find no cause for this. Is it possible this is a bug on the implementation side of things?

**Comment by jkoritzinsky** [comment]
It's from [here](https://github.com/KSP-SpaceDock/KerbalStuff/commit/edf9982b1299137b67f5fec4452964a8fa0ad22c#diff-cd155127a0c7869ac48510331ddcb662L9).  Just a simple typo during the rebranding.

**Comment by ThomasKerman** [comment]
This commit has already been [reverted](https://github.com/KSP-SpaceDock/KerbalStuff/commit/2d5d87ccce9ec9eb542a0a29a9c5f77f13d56b72) and replaced with a [better integration](https://github.com/KSP-SpaceDock/KerbalStuff/pull/6) that makes it more modular.

Please always check the current master for the state of the things, before you open an issue. Closing.
